instance: cerntraining.service-now.com
auth:
    type: sso_oauth
    sso_method: kerberos
    oauth_client_id: 6405e..........
    oauth_client_secret: sdazh8........
session:
    cookie_file: mycookie.txt
    oauth_tokens_file: mytoken
log_file : mylog.txt
