instance: cerntraining.service-now.com
auth:
    type: kerberos
    oauth_client_id: 6405e..........
    oauth_client_secret: sdazh8........
session:
    cookie_file: cookie.txt
    oauth_tokens_file: tokens.txt
log:
    log_enabled: true
    log_file_path : log.txt
    log_level: DEBUG
    log_format: %(asctime)s [%(name)s] [%(levelname)s] %(message)s
    log_file_size_bytes: 1000000
    log_file_rotations: 10
    log_file_encoding: utf-8
